### ISSUE TITLE
Changing break tag output

### ISSUE THREAD

**Issue by smaili** [pugjs/jade#2183] opened 2015-12-11 06:57 UTC
Would it be possible for `br` and `#[br]` be outputted as `<br>` or `<br />`?

I've noticed that right now it's outputting `<br></br>`, which Chrome is interpreting as two separate breaks, i.e., `<br><br>`.

**Comment by TimothyGu** [comment] 2015-12-13 17:11
Are you sure? Using the following:

```jade
br
| #[br]
```

on http://jade-lang.com/ correctly returns

```html
<br/><br/>
```

**Comment by ForbesLindesay** [comment] 2015-12-14 17:43
Closing, will re-open if you can provide an example that outputs incorrect code.

**Closed by ForbesLindesay** 2015-12-14 17:43 UTC

**Comment by smaili** [comment] 2015-12-18 04:56
Sorry for the delay.

Upon further testing, the aforementioned issue is occurring because of an xml doctype:

```Jade
doctype xml
svg( width='32px', height='32px', xmlns='http://www.w3.org/2000/svg', viewBox='0 0 100 100' )

p.
    #[br]
```

The result:
```html
<?xml version="1.0" encoding="utf-8" ?>
<svg width="32px" height="32px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"></svg>
<p><br></br></p>
```

**Comment by ForbesLindesay** [comment] 2015-12-18 12:49
That's expected behaviour because xml does not have html's list of self-closing tags.  You can use:

```jade
doctype xml
svg( width='32px', height='32px', xmlns='http://www.w3.org/2000/svg', viewBox='0 0 100 100' )

p.
    #[br/]
```

```html
<?xml version="1.0" encoding="utf-8" ?>
<svg width="32px" height="32px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"></svg>
<p><br/></p>
```

**Comment by smaili** [comment] 2015-12-18 19:32
Good to know! :+1:
