### ISSUE TITLE
Precise error handling when there is improper spacing in a line.

### ISSUE THREAD

**Issue by bgvianyc** [pugjs/jade#2166] opened 2015-11-15 16:08 UTC
The below code throws an error because of this line:

being `label(for='name')Your Name *` instead of `label(for='name') Your Name *`

However the error thrown points to a different line not indicating this is the cause of the error (see error).

```
      .typeahead-demo.typeahead-focus-trigger
        input.typeahead#main-typeahead(placeholder='Search for …')
        .btn-demo.is-pressed
      img.Typeahead-spinner(src="static/img/spinner.gif" style="margin-top: 20px; display: none;")
 
      form#manager-finder(action='#')
        div
          h3 Building Address
          section
            label(for='buildingAddress') Enter your building address
            input.typeahead.required#buildingAddress(name='buildingAddress' type='text')
          h3 Building Needs
          section
            label(for='name')Your Name *
            input.required#name(name='name' type='text')
            label(for='email')Email *
            input.required.email#email(name='email' type='text')
 ```

```
------
Error: /pyrn/views/home.jade:32
   30|       .typeahead-demo.typeahead-focus-trigger
   31|         input.typeahead#main-typeahead(placeholder='Search for building address or management company…')
 > 32|         .btn-demo.is-pressed
   33|       img.Typeahead-spinner(src="static/img/spinner.gif" style="margin-top: 20px; display: none;")
   34|    
   35|     div                           
 
Unexpected token `tag` expected `text`, `code`, `:`, `newline` or `eos`
   at Parser.tag (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:806:15)
   at Parser.parseTag (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:737:17)
   at Parser.parseExpr (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:211:21)
   at Parser.block (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:707:25)
   at Parser.tag (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:816:24)
   at Parser.parseTag (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:737:17)
   at Parser.parseExpr (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:211:21)
   at Parser.block (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:707:25)
   at Parser.tag (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:816:24)
   at Parser.parseTag (/var/lib/postgresql/pyrn/node_modules/jade/lib/parser.js:737:17)
```

**Comment by TimothyGu** [comment] 2015-11-17 20:33
Your test case throws a correct error in the latest version of Jade (1.11.0). Try putting in this snippet into http://jade-lang.com/, it shows (after fixing the indentation):

```
Jade:14
    12|     h3 Building Needs
    13|     section
  > 14|       label(for='name')Your Name *
    15|       input.required#name(name='name' type='text')
    16|       label(for='email')Email *
    17|       input.required.email#email(name='email' type='text')

Unexpected token `tag` expected `text`, `code`, `:`, `newline` or `eos`
```

Are you using includes or extends?

**Comment by bgvianyc** [comment] 2015-11-18 02:51
Yes, I'm using extends.

**Comment by ForbesLindesay** [comment] 2016-03-15 12:37
Closing as I'm not able to reproduce with the latest version of pug.

**Closed by ForbesLindesay** 2016-03-15 12:37 UTC
Labels: Error Reporting
