### ISSUE TITLE
Process attributes (links)

### ISSUE THREAD

**Issue by deni35** [pugjs/jade#2224] opened 2016-01-24 18:18 UTC
I need to change href and src attributes on compile stage and also render stage.
Is there way to iterate each attribute and change them?

For example: I need to add en/ and ru/ prefix to links which point to html files.

**Comment by TimothyGu** [comment] 2016-01-24 18:20
No. Use a function instead:

```js
locals.getHref = function getHref(orig) {
  // magic
  return orig;
};
```

```jade
a(href=getHref('https://github.com'))
```

**Comment by deni35** [comment] 2016-01-24 18:29
Could you add this feature in next versions?

**Comment by ForbesLindesay** [comment] 2016-01-25 13:16
You could write a plugin for pug@2.0.0 to do this, but you'd probably be better off just doing what @TimothyGu suggests and wrapping all your href values in a call to a given function, which you can then pass in via locals.  You can do this today.  It doesn't require intimate knowledge of pug's internals, and it is guaranteed to keep working though all future versions of pug (whereas a plugin may need to be updated frequently).

**Comment by deni35** [comment] 2016-01-26 22:32
if I forget to use the function, link will not work. This should be automated.
Also I want to replace automatically all scripts and styles onto one common.js and common.css.
What is pug@2.0.0? Is there example of plugins?

**Comment by TimothyGu** [comment] 2016-01-27 00:15
An example: https://github.com/pugjs/jade-plugin-debug-line

**Comment by deni35** [comment] 2016-01-27 11:58
Thanks. But is it okey that 'jade-plugin-debug-line' is not in the npm registry ?
And I can't find information how to make jade use plugin.

**Comment by jeromew** [comment] 2016-01-27 16:40
plugins are a work in progress. If you are looking for an out-of-the-box solution with jade, stick with @TimothyGu 's proposal even if yes, if you forget to call the function, the transformation won't be applied.

you can also post-process the html page with something as https://github.com/substack/node-trumpet.

you could also hide @TimothyGu's proposal in a mixin

    mixin a(href)
      a(href=getHref(href))
        block

and then use

    +a('https://github.com')
      | click here

**Comment by ForbesLindesay** [comment] 2016-01-27 16:51
I'm going to close this issue as everything is working as intended.  Two solutions have been proposed (one which works today, one which is already a work in progress).

**Closed by ForbesLindesay** 2016-01-27 16:51 UTC
Labels: plugin-request

**Comment by deni35** [comment] 2016-01-27 18:33
**jeromew**, I like your idea with the mexin, but I can't use a classes.
I've seen this way: ``+link('/foo', 'foo')(class="btn")`` but I don't like it. 
I'de like so: ``+a.btn.btn-primary("index.html") Home``

I thought about post-process the html, but I'm afraid it will be very slow.

I hope I will manage to make it via a plugin.
